# Generated by Django 3.2.3 on 2023-12-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
