# Generated by Django 3.2.3 on 2023-12-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0003_auto_20231204_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
    ]
