# Generated by Django 3.2.3 on 2024-01-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0005_auto_20231231_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
    ]
