# Generated by Django 3.2.3 on 2024-01-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0007_meal_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.DeleteModel(
            name='NutritionPlan',
        ),
    ]
